### ISSUE TITLE
softmax->alpha, Gumbel-Softmax->ratio?

### ISSUE THREAD

**Issue by yiyunchen** [VITA-Group/AGD#6]
Hello, I am new to NAS.
In your paper, you choose softmax for alpha search while using Gumbel-Softmax for ratio, why? Can they both use Gumbel-Softmax?

Thank you!

**Comment by tilmto** [comment]
We use softmax for alpha (indicating different operators) following [DARTS](https://arxiv.org/abs/1806.09055) which is also a common solution in NAS. We use gumbel-softmax to sample only one choice for ratio (indicating different output channels), i.e., during each iteration only one channel choice is activated, to save GPU memory. If we also use softmax for ratio, then we need to load several copies of weight with different channels in GPU memory, which will greatly limit the total search space.
Actually, it's totally OK to use gumbel-softmax for both of them and you can take a look at [FBNetV2](https://openaccess.thecvf.com/content_CVPR_2020/html/Wan_FBNetV2_Differentiable_Neural_Architecture_Search_for_Spatial_and_Channel_Dimensions_CVPR_2020_paper.html) which uses gumbel-softmax (soft version, instead of our hard version) for both operators and channels.
