### ISSUE TITLE
About save after quantized

### ISSUE THREAD

**Issue by shenshen0318** [VITA-Group/AGD#9]
Hello!

First of all awesome code and article.
I want to know how to save the model after quantized. Because of the operator dequantize，we got the float32 during the train.
I hope you could reply at your convenience.

**Comment by tilmto** [comment]
Hi, since we use the linear quantizer (see [QAT](https://arxiv.org/abs/1712.05877)) for quantizing weight and activation, the weight and activation can be determined after training based on their max/min range. Therefore, you can calculate the k-bit quantized weight as 1/S * round(S * W) where W is the weight and S=(2**k-1) / (W_max - W_min). Hope this is helpful for you.

**Comment by shenshen0318** [comment]
Thank you for your reply. After training we get the .pth file inclulding scale and range, so I need further processing to get the weight and activation. Is it right?

**Comment by tilmto** [comment]
Yes

**Comment by shenshen0318** [comment]
Thanks.
